### ISSUE TITLE
[Copy] Export description needs updating now that private keys are exported

### ISSUE THREAD

**Issue by Soleone** [EOSEssentials/Scatter#116]
Telegram user `@Fow` noted that the following is now incorrect:

![image](https://user-images.githubusercontent.com/2923/41815435-f568e66c-7738-11e8-97c7-883bb7814566.png)

The copy should be updated in the english version and other languages.

Sidenote: A good time to think about how to handle updating of existing translation strings. Somehow the original translators should be made aware that an update to a certain region is required.

**Comment by nsjames** [comment]
611ad9ee9e7c2230c8bea5233351c3a8501ca9af

**Comment by nsjames** [comment]
> Sidenote: A good time to think about how to handle updating of existing translation strings. Somehow the original translators should be made aware that an update to a certain region is required.

Indeed. At first I was reluctant to add new features or change things because of updates to localization. I quickly let go of that fear, and now there is a lot of changes in the English translation file as well as new keys which don't match/exist in other translations.

Perhaps some kind of diff tool that checks the last commit of a language against changes to the english from that timestamp.
