### ISSUE TITLE
Ehancement: Display all actions instead of only the first in the transaction.

### ISSUE THREAD

**Issue by kasperfish** [EOSEssentials/Scatter#99]
So scatter only shows the first action in a transaction. I think this could be a potential flaw because there could be a hidden transfer in the transaction. Also it will give the user a better idea of whats going to happen. as example: create account, delegate bw, buy ram. Only The newaccount action is displayed. Also the scrollable info on the right is not that meaningful for the average user.
![image](https://user-images.githubusercontent.com/5130772/41500647-1d4763aa-7196-11e8-9fb1-c4215a55a271.png)

**Comment by nsjames** [comment]
Yo, find me on Telegram. I want to thank you for this and see if there's a way to return the favor. 
You found a user-experience vulnerability. 

I wish I had seen this sooner, as it only took about 20 minutes to fix and could have been very bad with this posted on GitHub and not brought to my attention personally.

Fixed in b58509ad6573df93726950b8b9de0780715cebd6
